# Generated by Django 3.1.4 on 2021-01-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210117_0926'),
        ('list_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItem',
            new_name='ListItemModel',
        ),
    ]
